# create namespace
# => kubectl create namespace dm-benchmark-multiple-es-ztoo-g3-s-90
# switch namespace
# => kubectl config set-context --current --namespace=dm-benchmark-multiple-es-ztoo-g3-s-90
#
#
# to make template invoke the following:
# => helm dependency update charts/zeebe-benchmark && helm template dm-bmrk-m-ztoo-g3-s-90 charts/zeebe-benchmark -f kind/multiple-es-instances-ztoo-g3-s-90-values.yaml --output-dir out/multiple/multiple-es-ztoo-values-g3-s-90
#
# to install charts invoke the following:
# => helm dependency update charts/zeebe-benchmark && helm install dm-bmrk-m-ztoo-g3-s-90 charts/zeebe-benchmark -f kind/multiple-es-instances-ztoo-g3-s-90-values.yaml --render-subchart-notes
#
# to uninstall charts invoke the following:
# => helm uninstall dm-bmrk-m-ztoo-g3-s-90 && kubectl delete pvc -l app.kubernetes.io/instance=dm-bmrk-m-ztoo-g3-s-90 && kubectl delete pvc -l release=dm-bmrk-m-ztoo-g3-s-90
#
# delete namespace
# => kubectl delete namespace dm-benchmark-multiple-es-ztoo-g3-s-90
#

global:
  identity:
    auth:
      enabled: false

camunda-platform:
  global:
    elasticsearch:
      zeebe:
        host: "{{ .Release.Name }}-elasticsearch-zeebe"
        clusterName: "zeebe-cluster"
      tasklist:
        host: "{{ .Release.Name }}-elasticsearch-tasklist"
        clusterName: "tasklist-cluster"
      operate:
        host: "{{ .Release.Name }}-elasticsearch-operate"
        clusterName: "operate-cluster"
      optimize:
        host: "{{ .Release.Name }}-elasticsearch-optimize"
        clusterName: "optimize-cluster"
  zeebe:
    retention:
      enabled: true
      ## @param zeebe.retention.minimumAge defines how old the data must be, before the data is deleted as a duration.
      minimumAge: 2d
    resources:
      limits:
        # default 4Gi
        memory: "4Gi"
        # default 1350m
        cpu: "2000m"
      requests:
        # default 4Gi
        memory: "4Gi"
        # default 1350m
        cpu: "1350m"

  zeebe-gateway:
    resources:
      limits:
        # default 400Mi
        memory: "2Gi"
        # default 450m
        cpu: "2000m"
      requests:
        # default 400Mi
        memory: "1Gi"
        # default 450m
        cpu: "1000m"

  operate:
    enabled: true
    retention:
      enabled: true
      minimumAge: 1d

  tasklist:
    enabled: true
    retention:
      enabled: true
      minimumAge: 1d

  optimize:
    enabled: true
    retention:
      enabled: true
      # triggered every hour => https://crontab.guru/#0_*_*_*_*
      cronTrigger: "0 * * * *"
      # https://docs.oracle.com/javase/9/docs/api/java/time/Period.html#parse-java.lang.CharSequence-
      ttl: "P1D"
      processDataCleanup:
        enabled: true
      decisionDataCleanup:
        enabled: true
      ingestedEventCleanup:
        enabled: true
      externalVariableCleanup:
        enabled: true
    archiver:
      enabled: true
    elasticSearch:
      indexNumberOfReplicas: 0

  elasticsearch:
    enabled: false

  elasticsearch-zeebe:
    enabled: true
    master:
      replicaCount: 1
      heapSize: 512m
      persistence:
        size: 128Gi
      resources:
        limits:
          memory: "1Gi"
          cpu: "3000m"
        requests:
          memory: "1Gi"
          cpu: "2000m"

  elasticsearch-tasklist:
    enabled: true
    master:
      replicaCount: 1
      heapSize: 512m
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "500m"

  elasticsearch-operate:
    enabled: true
    master:
      replicaCount: 1
      persistence:
        size: 128Gi
      resources:
        limits:
          memory: "2Gi"
          cpu: "3000m"
        requests:
          memory: "2Gi"
          cpu: "2000m"

  elasticsearch-optimize:
    enabled: true
    master:
      replicaCount: 1
      persistence:
        size: 128Gi
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
        requests:
          memory: "2Gi"
          cpu: "500m"

starter:
  rate: 90

worker:
  replicas: 1

timer:
  replicas: 0
  rate: 5

publisher:
  replicas: 0
  rate: 5

retentionPolicy:
  enabled: false

prometheus-elasticsearch-exporter:
  enabled: false

prometheus-elasticsearch-exporter-zeebe:
  enabled: true
  es:
    uri: http://{{ .Release.Name }}-elasticsearch-zeebe:9200
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring

prometheus-elasticsearch-exporter-tasklist:
  enabled: true
  es:
    uri: http://{{ .Release.Name }}-elasticsearch-tasklist:9200
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring

prometheus-elasticsearch-exporter-operate:
  enabled: true
  es:
    uri: http://{{ .Release.Name }}-elasticsearch-operate:9200
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring

prometheus-elasticsearch-exporter-optimize:
  enabled: true
  es:
    uri: http://{{ .Release.Name }}-elasticsearch-optimize:9200
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring