# create namespace
# => kubectl create namespace dm-benchmark-single-es-ztoo-g3-s-90
# switch namespace
# => kubectl config set-context --current --namespace=dm-benchmark-single-es-ztoo-g3-s-90
#
# update dependencies
# => helm dependency update charts/zeebe-benchmark
#
# to make template invoke the following:
# => helm template dm-bmrk-s-ztoo-g3-s-90 charts/zeebe-benchmark -f kind/single-es-instance-ztoo-g3-s-90-values.yaml --output-dir out/single/single-es-ztoo-values-g3-s-90
#
# to install charts invoke the following:
# => helm dependency update charts/zeebe-benchmark && helm install dm-bmrk-s-ztoo-g3-s-90 charts/zeebe-benchmark -f kind/single-es-instance-ztoo-g3-s-90-values.yaml --render-subchart-notes
#
#
# to uninstall charts invoke the following:
# => helm uninstall dm-bmrk-s-ztoo-g3-s-90 && kubectl delete pvc -l app.kubernetes.io/instance=dm-bmrk-s-ztoo-g3-s-90 && kubectl delete pvc -l release=dm-bmrk-s-ztoo-g3-s-90
#
# delete namespace
# => kubectl delete namespace dm-benchmark-single-es-ztoo-g3-s-90
#

global:
  identity:
    auth:
      enabled: false

camunda-platform:
  global:
    elasticsearch:
      zeebe:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      tasklist:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      operate:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      optimize:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"

  zeebe:
    retention:
      enabled: true
      ## @param zeebe.retention.minimumAge defines how old the data must be, before the data is deleted as a duration.
      minimumAge: 2d
    resources:
      limits:
        # default 4Gi
        memory: "4Gi"
        # default 1350m
        cpu: "2000m"
      requests:
        # default 4Gi
        memory: "4Gi"
        # default 1350m
        cpu: "1350m"

  zeebe-gateway:
    resources:
      limits:
        # default 400Mi
        memory: "2Gi"
        # default 450m
        cpu: "2000m"
      requests:
        # default 400Mi
        memory: "1Gi"
        # default 450m
        cpu: "1000m"

  operate:
    enabled: true
    retention:
      enabled: true
      minimumAge: 1d

  tasklist:
    enabled: true
    retention:
      enabled: true
      minimumAge: 1d

  optimize:
    enabled: true
    retention:
      enabled: true
      # triggered every hour => https://crontab.guru/#0_*_*_*_*
      cronTrigger: "0 * * * *"
      # https://docs.oracle.com/javase/9/docs/api/java/time/Period.html#parse-java.lang.CharSequence-
      ttl: "P1D"
      processDataCleanup:
        enabled: true
      decisionDataCleanup:
        enabled: true
      ingestedEventCleanup:
        enabled: true
      externalVariableCleanup:
        enabled: true
    archiver:
      enabled: true
    elasticSearch:
      indexNumberOfReplicas: 0

  identity:
    enabled: false

  elasticsearch:
    enabled: true
    master:
      replicaCount: 1
      heapSize: 3072m
      persistence:
        size: 192Gi
      resources:
        limits:
          memory: "6Gi"
          cpu: "3000m"
        requests:
          memory: "6Gi"
          cpu: "2000m"

  elasticsearch-zeebe:
    enabled: false

  elasticsearch-tasklist:
    enabled: false

  elasticsearch-optimize:
    enabled: false

  elasticsearch-operate:
    enabled: false

retentionPolicy:
  enabled: false

starter:
  rate: 90

worker:
  replicas: 1

timer:
  replicas: 0
  rate: 5

publisher:
  replicas: 0
  rate: 5

prometheus-elasticsearch-exporter:
  es:
    uri: http://{{ .Release.Name }}-elasticsearch:9200