# create namespace
# => kubectl create namespace dm-benchmark-single-es-instance-all-apps-enabled
# switch namespace
# => kubectl config set-context --current --namespace=dm-benchmark-single-es-instance-all-apps-enabled
#
#
# to make template invoke the following:
# => helm dependency update charts/zeebe-benchmark && helm template dm-benchmark-s charts/zeebe-benchmark -f kind/single-es-instance-all-apps-enabled-values.yaml --output-dir out_single/single-es-all-apps-enabled-values
#
# to install charts invoke the following:
# => helm dependency update charts/zeebe-benchmark && helm install dm-benchmark-s charts/zeebe-benchmark -f kind/single-es-instance-all-apps-enabled-values.yaml --render-subchart-notes
#
#
# to uninstall charts invoke the following:
# => helm uninstall dm-benchmark-s && kubectl delete pvc -l app.kubernetes.io/instance=dm-benchmark-s && kubectl delete pvc -l release=dm-benchmark-s
#
# delete namespace
# => kubectl delete namespace dm-benchmark-single-es-instance-all-apps-enabled
#

camunda-platform:
  global:
    elasticsearch:
      zeebe:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      tasklist:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      operate:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"
      optimize:
        host: "{{ .Release.Name }}-elasticsearch"
        clusterName: "elastic-cluster"

  zeebe:
    # ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
    #cpuThreadCount: "3"
    # ZEEBE_BROKER_THREADS_IOTHREADCOUNT
    #ioThreadCount: "3"
    #env:
    #  - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
    #    value: "0.87"
    #  - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
    #    value: "0.85"
    retention:
      enabled: true
      ## @param zeebe.retention.minimumAge defines how old the data must be, before the data is deleted as a duration.
      minimumAge: 5m
    #resources:
    #  limits:
    #    memory: "4Gi"
    #    cpu: "2000m"
    #  requests:
    #    memory: "4Gi"
    #    cpu: "1350m"

  #zeebe-gateway:
  #  env:
  #    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
  #      value: "2"
  #  resources:
  #    limits:
  #      memory: "2Gi"
  #      cpu: "2000m"
  #    requests:
  #      memory: "1Gi"
  #      cpu: "1000m"

  operate:
    enabled: true
    resources:
      requests:
        memory: "250Mi"
        cpu: "400m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

  tasklist:
    enabled: true
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: "400Mi"
        cpu: "400m"

  optimize:
    enabled: false
    resources:
      limits:
        memory: "4Gi"
        cpu: "1500m"
      requests:
        memory: "1500Mi"
        cpu: "500m"

  identity:
    enabled: false

  postgresql:
    enabled: false

  elasticsearch:
    enabled: true
    master:
      resources:
        limits:
          memory: "10Gi"
          cpu: "4000m"
        requests:
          memory: "6Gi"
          cpu: "2000m"

  elasticsearch-zeebe:
    enabled: false

  elasticsearch-tasklist:
    enabled: false

  elasticsearch-optimize:
    enabled: false

  elasticsearch-operate:
    enabled: false

retentionPolicy:
  enabled: true
  # Every 5 minutes => https://crontab.guru/#*/5_*_*_*_*
  schedule: "*/5 * * * *"
  policies:
    - name: zeebe-
      maxSize:
      unit: minutes
      timeToLive: 14
    - name: operate-
      unit: minutes
      timeToLive: 12
    - name: tasklist-
      unit: minutes
      timeToLive: 10
    # the following are not consumed by operate so we want to get rid of them rather quickly
    - name: zeebe-record_message
      maxSize: 1
    - name: zeebe-record_process-instance-creation
      maxSize: 1

starter:
  rate: 5

worker:
  replicas: 1

timer:
  replicas: 1
  rate: 5

publisher:
  replicas: 1
  rate: 5

prometheus-elasticsearch-exporter:
  es:
    uri: http://{{ .Release.Name }}-elasticsearch:9200