---
apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    app.kubernetes.io/component: zeebe-client
    {{- include "zeebe-benchmark.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: zeebe-client
  ports:
  - name: http
    port: 9600
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clients
  labels:
    release: monitoring
    {{- include "zeebe-benchmark.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: zeebe-client
  endpoints:
  - honorLabels: true
    # since - is not supported directly, we have to use the index function and quote "camunda-platform"
    interval: {{ index .Values "camunda-platform" "prometheusServiceMonitor" "scrapeInterval" }}
    path: /prometheus
    port: http