{{- if and .Values.saas.enabled (not .Values.saas.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeebe-benchmark.credentials-name" .}}
type: Opaque
stringData:
  clientId: {{ .Values.saas.credentials.clientId }}
  clientSecret: {{ .Values.saas.credentials.clientSecret }}
  zeebeAddress: {{ .Values.saas.credentials.zeebeAddress }}
  authServer: {{ .Values.saas.credentials.authServer }}
{{- end }}