{{- if .Values.retentionPolicy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-benchmark-curator-config
  labels:
    {{- include "zeebe-benchmark.labels" . | nindent 4 }}
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
      {{- $counter := 1 | int }}
      {{- range $policy := .Values.retentionPolicy.policies }}
      {{ $counter }}:
      {{- if $policy.timeToLive }}
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
          - filtertype: pattern
            kind: prefix
            value: {{ $policy.name }}
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y-%m-%d'
            unit: days
            unit_count: {{ $policy.timeToLive }}
            field:
            stats_result:
            epoch:
            exclude: False
      {{- else }}
        action: delete_indices
        description: "Clean up ES by deleting too big indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
          - filtertype: pattern
            kind: prefix
            value: zeebe-
          - filtertype: space
            disk_space: {{ $policy.maxSize }}
            source: name
            timestring: '%Y-%m-%d'
      {{- end }}
      {{- $counter = add1 $counter }}
      {{- end }}
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - elasticsearch-master-headless
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
{{- end }}