apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: {{ .Values.worker.replicas }}
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: worker
          image: "{{ .Values.global.image.repository }}/worker:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl={{ .Release.Name }}-zeebe-gateway:26500
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity={{ .Values.worker.capacity }}
                -Dapp.worker.pollingDelay=1ms
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: worker-config
                optional: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"