apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: gcr.io/zeebe-io/starter:SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=default-zeebe-gateway:26500
                -Dapp.starter.rate=100
                -Dzeebe.client.requestTimeout=62000
                -XX:+HeapDumpOnOutOfMemoryError
                -Dapp.starter.bpmnXmlPath=bpmn/msg_one_task.bpmn
                -Dapp.starter.startViaMessage=true
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: publisher-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
