---
# Source: zeebe-benchmark/charts/prometheus-elasticsearch-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: zeebe-benchmark-test-prometheus-elasticsearch-exporter
  labels:
    helm.sh/chart: prometheus-elasticsearch-exporter-6.4.0
    app.kubernetes.io/name: prometheus-elasticsearch-exporter
    app.kubernetes.io/instance: zeebe-benchmark-test
    app.kubernetes.io/version: "v1.7.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9108
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus-elasticsearch-exporter
    app.kubernetes.io/instance: zeebe-benchmark-test
