apiVersion: v2
name: zeebe-benchmark
description: A Helm chart for Zeebe benchmarks
type: application
version: 0.3.27
appVersion: "8.2.5"
sources:
  - https://github.com/camunda/zeebe-benchmark-helm
  - https://github.com/camunda/camunda
dependencies:
  - name: camunda-platform
    repository: "https://helm.camunda.io"
    version: "13.0.0-alpha8"
    condition: "camunda-platform.enabled"
  - name: prometheus-elasticsearch-exporter
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 6.4.0
    condition: "prometheus-elasticsearch-exporter.enabled"
maintainers:
  - name: ChrisKujawa
    email: christopher.zell@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Zeebe Repo
      url: https://github.com/camunda/camunda
    - name: Zeebe Docs
      url: https://docs.camunda.io/docs/components/zeebe/zeebe-overview/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: "- kind: added\n  description: \"change retention to 1h.\"\n- kind: fixed\n  description: \"golden files.\"\n- kind: fixed\n  description: \"change retention to 70m for safety\"\n- kind: fixed\n  description: \"fix golden files.\"\n"
