apiVersion: v2
name: zeebe-benchmark
description: A Helm chart for Zeebe benchmarks
type: application
version: 0.2.3
appVersion: "8.2.5"
sources:
  - https://github.com/zeebe-io/benchmark-helm
  - https://github.com/camunda/camunda
dependencies:
  - name: camunda-platform
    repository: "oci://ghcr.io/camunda/helm"
    version: "0.0.0-8.6.0-alpha4"
    condition: "camunda.enabled"
  - name: prometheus-elasticsearch-exporter
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 5.2.0
    condition: "prometheus-elasticsearch-exporter.enabled"
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Zeebe Repo
      url: https://github.com/camunda/camunda
    - name: Zeebe Docs
      url: https://docs.camunda.io/docs/components/zeebe/zeebe-overview/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: "- kind: added\n  description: \"add more details to NOTES\"\n"
