apiVersion: v2
name: zeebe-benchmark
description: A Helm chart for Zeebe benchmarks
type: application
version: 0.2.2
appVersion: "8.2.5"
sources:
  - https://github.com/zeebe-io/benchmark-helm
  - https://github.com/camunda/camunda
dependencies:
  - name: camunda-platform
    repository: "https://helm.camunda.io"
    version: 10.3.2
    condition: "camunda.enabled"
  - name: prometheus-elasticsearch-exporter
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 5.2.0
    condition: "prometheus-elasticsearch-exporter.enabled"
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Zeebe Repo
      url: https://github.com/camunda/camunda
    - name: Zeebe Docs
      url: https://docs.camunda.io/docs/components/zeebe/zeebe-overview/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: "- kind: changed\n  description: \"load config as additional spring config\"\n- kind: changed\n  description: \"set tag on all components\"\n- kind: changed\n  description: \"change zeebe-gateway to zeebeGateway\"\n- kind: changed\n  description: \"disable identityKeycloak\"\n- kind: changed\n  description: \"rename camunda/zeebe repo\"\n"
