apiVersion: v2
name: zeebe-benchmark
description: A Helm chart for Zeebe benchmarks
type: application
version: 0.3.4
appVersion: "8.2.5"
sources:
  - https://github.com/zeebe-io/benchmark-helm
  - https://github.com/camunda/camunda
dependencies:
  - name: camunda-platform
    repository: "oci://ghcr.io/camunda/helm"
    version: "0.0.0-rc-8.6"
    condition: "camunda.enabled"
  - name: prometheus-elasticsearch-exporter
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 6.4.0
    condition: "prometheus-elasticsearch-exporter.enabled"
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Zeebe Repo
      url: https://github.com/camunda/camunda
    - name: Zeebe Docs
      url: https://docs.camunda.io/docs/components/zeebe/zeebe-overview/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: "- kind: added\n  description: \"introduce worker threads\"\n- kind: added\n  description: \"remove repeated completion delay, and only add this if not set.\"\n- kind: fixed\n  description: \"regen threads\"\n- kind: fixed\n  description: \"increase worker threads\"\n- kind: fixed\n  description: \"use larger disks to avoid throttling\"\n"
