# Example values file for a realistic Zeebe benchmark.
global:
  # Disable global ingress
  ingress:
    enabled: false
  # Image configuration to be used in each sub chart
  image:
    # Image.repository defines the repository from which to fetch the docker images
    repository: "gcr.io/zeebe-io"
    # Image.tag defines the tag / version which should be used in the chart
    tag: SNAPSHOT
    # Image.pullPolicy defines the image pull policy which should be used https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
    pullPolicy: Always
  # Disable Identity completely; both this flag and `camunda-platform.identity.enabled` are required.
  identity:
    auth:
      enabled: false
  elasticsearch:
    disableExporter: true
#################################################################################################
#################################################################################################
#################################################################################################


camunda-platform:
  enabled: true
  global:

    elasticsearch:
      disableExporter: true


  zeebe:
    partitionCount: 32
    # Image configuration to configure the zeebe image specifics
    image:
      # Image.repository defines which image repository to use
      repository: camunda/zeebe
      tag: SNAPSHOT

    # Retention can be used to define the data in Elasticsearch (ILM).
    retention:
      ## @param zeebe.retention.enabled if true, the ILM Policy is created and applied to the index templates.
      enabled: true
      ## @param zeebe.retention.minimumAge defines how old the data must be, before the data is deleted as a duration.
      minimumAge: 1d # set it to a higher value if we run with operate, so operate has enough time to consume the data

    # Resources configuration to set request and limit configuration for the container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limitsS
    resources:
      limits:
        cpu: 3
        memory: 8Gi
      requests:
        cpu: 3
        memory: 8Gi

  zeebeGateway:
    # Replicas defines how many standalone gateways are deployed
    replicas: 2

    # Image configuration to configure the zeebe-gateway image specifics
    image:
      # Image.repository defines which image repository to use
      repository: camunda/zeebe
      tag: SNAPSHOT

    env:
      - name: CAMUNDA_SECURITY_AUTHENTICATION_METHOD
        value: "BASIC"
      - name: CAMUNDA_SECURITY_AUTHENTICATION_BASIC_ALLOWUNAUTHENTICATEDAPIACCESS
        value: "true"

    # Resources configuration to set request and limit configuration for the container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi

  operate:
    enabled: false

  # ELASTIC
  elasticsearch:
    enabled: true
    imageTag: 8.9.2

    master:
      fullnameOverride: elastic
      nameOverride: elastic
      # Number of master-elegible replicas to deploy
      replicaCount: 3
      pdb:
        minAvailable: 2
      # Elasticsearch master-eligible node heap size.
      # Will be converted to -Xms3g
      heapSize: 3g
      # The resources configurations for elasticsearch containers
      resources:
        requests:
          cpu: 1
          memory: 3Gi
        limits:
          cpu: 2
          memory: 6Gi
      persistence:
        # Persistent Volume Storage Class
        storageClass: "ssd"
        # Persistent Volume Size
        size: 128Gi
        # Persistent Volume Access Modes
        accessModes: [ "ReadWriteOnce" ]
