---
# Source: zeebe-benchmark/templates/starter.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
  labels:
    app: starter
spec:
  selector:
    matchLabels:
      app: starter
  replicas: 1
  template:
    metadata:
      labels:
        app: starter
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: starter
          image: "gcr.io/zeebe-io/starter:ck-main-exporter-8611f3dc"
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl=zeebe-benchmark-test-zeebe-gateway:26500
                -Dapp.starter.rate=1
                -Dapp.starter.durationLimit=0
                -Dzeebe.client.requestTimeout=62000
                -Dapp.starter.processId="bankDisputeHandling"
                -Dapp.starter.bpmnXmlPath="bpmn/realistic/bankCustomerComplaintDisputeHandling.bpmn"
                -Dapp.starter.extraBpmnModels.0="bpmn/realistic/refundingProcess.bpmn"
                -Dapp.starter.extraBpmnModels.1="bpmn/realistic/determineFraudRatingConfidence.dmn"
                -Dapp.starter.businessKey="customerId"
                -Dapp.starter.payloadPath="bpmn/realistic/realisticPayload.json"
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "INFO"
          envFrom:
            - configMapRef:
                name: starter-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"
