name: Go CI

on:
  push:
    branches: [ main ]
  pull_request: { }

env:
  HELM_VERSION: 3.11.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Go Format
      run: |
        make go.fmt
        diff=$(git status --porcelain)
        if [ -n "$diff" ]
        then
          echo "Some files are not following the go format ($diff), run gofmt and fix your files."
          exit 1
        fi
    - name: Install License Tool
      run: make go.addlicense-install
    - name: Check License
      run: make go.addlicense-check
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: "${{ env.HELM_VERSION }}"
    - name: Helm Add Repo
      run: make helm.repos-add
    - name: Test
      run: make go.test
  auto-merge:
    name: Auto-merge dependency PRs
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'camunda/zeebe-benchmark-helm' && (github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]')
    permissions:
      checks: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: merge
        name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: "${{ secrets.AUTO_MERGE_GITHUB_TOKEN }}"
